[phases.setup]
nixPkgs = ["...", "dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore BingoProject.csproj",
  "dotnet publish BingoProject.csproj -c Release -o out"
]

[start]
cmd = "cd out && dotnet BingoProject.dll"